[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "podcasts-data"
version = "0.1.0"
workspace = "../"

[dependencies]
ammonia = "1.2.0"
chrono = "0.4.6"
derive_builder = "0.6.0"
lazy_static = "1.1.0"
log = "0.4.4"
rayon = "1.0.2"
rfc822_sanitizer = "0.3.3"
rss = "1.5.0"
url = "1.7.1"
xdg = "2.1.0"
xml-rs = "0.8.0"
futures = "0.1.23"
hyper = "0.12.11"
http = "0.1.13"
tokio = "0.1.11"
hyper-tls = "0.3.0"
native-tls = "0.2.1"
num_cpus = "1.8.0"
failure = "0.1.2"
failure_derive = "0.1.2"

[dependencies.diesel]
features = ["sqlite", "r2d2"]
version = "1.3.2"

[dependencies.diesel_migrations]
features = ["sqlite"]
version = "1.3.0"

[dev-dependencies]
rand = "0.5.5"
tempdir = "0.3.7"
pretty_assertions = "0.5.1"
maplit = "1.0.1"
