[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
build = "build.rs"
name = "podcasts-gtk"
version = "0.1.0"

[dependencies]
chrono = "0.4.6"
crossbeam-channel = "0.2.6"
gdk = "0.10.0"
gdk-pixbuf = "0.6.0"
glib = "0.7.0"
gstreamer = "0.13.0"
gstreamer-player = "0.13.0"
humansize = "1.1.0"
lazy_static = "1.2.0"
log = "0.4.6"
loggerv = "0.7.1"
open = "1.2.2"
rayon = "1.0.3"
url = "1.7.2"
failure = "0.1.3"
failure_derive = "0.1.3"
fragile = "0.3.0"
regex = "1.0.6"
reqwest = "0.9.5"
serde_json = "1.0.33"
# html2text = "0.1.8"
html2text = { git = "https://github.com/alatiera/rust-html2text" }
gettext-rs = { git = "https://github.com/danigm/gettext-rs", branch = "no-gettext", features = ["gettext-system"] }

[dependencies.gtk]
features = ["v3_24"]
version = "0.6.0"

[dependencies.gio]
features = ["v2_50"]
version = "0.6.0"

[dependencies.libhandy]
version = "0.3.0"
features = [ "v0_0_7"]

[dependencies.mpris-player]
version = "0.2.0"
git = "https://gitlab.gnome.org/World/Rust/mpris-player"

[dependencies.podcasts-data]
path = "../podcasts-data"

[dependencies.podcasts-downloader]
path = "../podcasts-downloader"

[dev-dependencies]
pretty_assertions = "0.5.1"
